name: Eslint check
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
          cache: 'npm'
      - name: Install modules
        run: npm install
      - name: Run ESLint
        run: npm run lint:check
      - name: Run TS lint
        run: npm run lint:tsc
      - name: Check Prettier
        run: npm run format:check
      - name: Run unit test
        run: npm run test
